<img src="../../../images/banners/pandas-cropped.jpeg" width="600"/>

<a class="anchor" id="essential_basic_functionality"></a>
# <img src="../../../images/logos/pandas.png" width="23"/> Sorting

## <img src="../../../images/logos/toc.png" width="20"/> Table of Contents 

* [By index](#by_index)
* [By values](#by_values)
* [By indexes and values](#by_indexes_and_values)
* [searchsorted](#searchsorted)
* [smallest / largest values](#smallest_/_largest_values)
* [Sorting by a MultiIndex column](#sorting_by_a_multiindex_column)

---

In [1]:
import pandas as pd
import numpy as np

pandas supports three kinds of sorting: sorting by index labels,
sorting by column values, and sorting by a combination of both.

<a class="anchor" id="by_index"></a>
### By index

The [`Series.sort_index()`](../reference/api/pandas.Series.sort_index.html#pandas.Series.sort_index "pandas.Series.sort_index") and [`DataFrame.sort_index()`](../reference/api/pandas.DataFrame.sort_index.html#pandas.DataFrame.sort_index "pandas.DataFrame.sort_index") methods are
used to sort a pandas object by its index levels.

In [2]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)
df

one       two     three
a -1.450903  0.033145       NaN
b  0.501378  1.551141 -0.466256
c  0.057612  1.402359  1.580910
d       NaN  0.610380 -1.654630

In [3]:
unsorted_df = df.reindex(
    index=["a", "d", "c", "b"], columns=["three", "two", "one"]
)
unsorted_df

three       two       one
a       NaN  0.033145 -1.450903
d -1.654630  0.610380       NaN
c  1.580910  1.402359  0.057612
b -0.466256  1.551141  0.501378

In [4]:
unsorted_df.sort_index()

three       two       one
a       NaN  0.033145 -1.450903
b -0.466256  1.551141  0.501378
c  1.580910  1.402359  0.057612
d -1.654630  0.610380       NaN

In [5]:
unsorted_df.sort_index(ascending=False)

three       two       one
d -1.654630  0.610380       NaN
c  1.580910  1.402359  0.057612
b -0.466256  1.551141  0.501378
a       NaN  0.033145 -1.450903

In [6]:
unsorted_df.sort_index(axis=1)

one     three       two
a -1.450903       NaN  0.033145
d       NaN -1.654630  0.610380
c  0.057612  1.580910  1.402359
b  0.501378 -0.466256  1.551141

In [7]:
unsorted_df["three"].sort_index()

a         NaN
b   -0.466256
c    1.580910
d   -1.654630
Name: three, dtype: float64

> **New in version 1.1.0**
> 
> Sorting by index also supports a `key` parameter that takes a callable
function to apply to the index being sorted. For `MultiIndex` objects,
the key is applied per-level to the levels specified by `level`.

In [8]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
    list("ab")
)

s1

c
a b   
B 1  2
a 2  3
C 3  4

In [9]:
s1.sort_index(level="a")

c
a b   
B 1  2
C 3  4
a 2  3

In [10]:
s1.sort_index(level="a", key=lambda idx: idx.str.lower())

c
a b   
a 2  3
B 1  2
C 3  4

For information on key sorting by value, see [value sorting](https://pandas.pydata.org/docs/user_guide/basics.html#basics-sort-value-key).

<a class="anchor" id="by_values"></a>
### By values

The [`Series.sort_values()`](../reference/api/pandas.Series.sort_values.html#pandas.Series.sort_values "pandas.Series.sort_values") method is used to sort a `Series` by its values. The
[`DataFrame.sort_values()`](../reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values "pandas.DataFrame.sort_values") method is used to sort a `DataFrame` by its column or row values.
The optional `by` parameter to [`DataFrame.sort_values()`](../reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values "pandas.DataFrame.sort_values") may used to specify one or more columns
to use to determine the sorted order.

In [11]:
df1 = pd.DataFrame(
    {"one": [2, 1, 1, 1], "two": [1, 3, 2, 4], "three": [5, 4, 3, 2]}
)

df1

one  two  three
0    2    1      5
1    1    3      4
2    1    2      3
3    1    4      2

In [12]:
df1.sort_values(by="two")

one  two  three
0    2    1      5
2    1    2      3
1    1    3      4
3    1    4      2

The `by` parameter can take a list of column names, e.g.:

In [13]:
df1[["one", "two", "three"]].sort_values(by=["one", "two"])

one  two  three
2    1    2      3
1    1    3      4
3    1    4      2
0    2    1      5

These methods have special treatment of NA values via the `na_position`
argument:

In [14]:
s = pd.Series(
    ["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"], dtype="string"
)
s[2] = np.nan

s

0       A
1       B
2    <NA>
3    Aaba
4    Baca
5    <NA>
6    CABA
7     dog
8     cat
dtype: string

In [15]:
s.sort_values()

0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
2    <NA>
5    <NA>
dtype: string

In [16]:
s.sort_values(na_position="first")

2    <NA>
5    <NA>
0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
dtype: string

New in version 1.1.0.

Sorting also supports a `key` parameter that takes a callable function
to apply to the values being sorted.

In [17]:
s1 = pd.Series(["B", "a", "C"])

In [18]:
s1.sort_values()

0    B
2    C
1    a
dtype: object

In [19]:
s1.sort_values(key=lambda x: x.str.lower())

1    a
0    B
2    C
dtype: object

`key` will be given the [`Series`](../reference/api/pandas.Series.html#pandas.Series "pandas.Series") of values and should return a `Series`
or array of the same shape with the transformed values. For `DataFrame` objects,
the key is applied per column, so the key should still expect a Series and return
a Series, e.g.

In [20]:
df = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3]})

df

a  b
0  B  1
1  a  2
2  C  3

In [21]:
df.sort_values(by="a")

a  b
0  B  1
2  C  3
1  a  2

In [22]:
df.sort_values(by="a", key=lambda col: col.str.lower())

a  b
1  a  2
0  B  1
2  C  3

The name or type of each column can be used to apply different functions to
different columns.

<a class="anchor" id="by_indexes_and_values"></a>
### By indexes and values

Strings passed as the `by` parameter to [`DataFrame.sort_values()`](../reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values "pandas.DataFrame.sort_values") may
refer to either columns or index level names.

In [23]:
idx = pd.MultiIndex.from_tuples(
    [("a", 1), ("a", 2), ("a", 2), ("b", 2), ("b", 1), ("b", 1)]
)

In [24]:
idx.names = ["first", "second"]
df_multi = pd.DataFrame({"A": np.arange(6, 0, -1)}, index=idx)
df_multi

A
first second   
a     1       6
      2       5
      2       4
b     2       3
      1       2
      1       1

Sort by ‘second’ (index) and ‘A’ (column)

In [25]:
df_multi.sort_values(by=["second", "A"])

A
first second   
b     1       1
      1       2
a     1       6
b     2       3
a     2       4
      2       5

> **Note:**
> 
> If a string matches both a column name and an index level name then a
warning is issued and the column takes precedence. This will result in an
ambiguity error in a future version.

<a class="anchor" id="searchsorted"></a>
### searchsorted

Series has the [`searchsorted()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.searchsorted.html#pandas.Series.searchsorted) method, which works similarly to
[`numpy.ndarray.searchsorted()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.searchsorted.html#numpy.ndarray.searchsorted "(in NumPy v1.23)").

In [26]:
ser = pd.Series([1, 2, 3])

In [27]:
ser.searchsorted([0, 3])

array([0, 2])

In [28]:
ser.searchsorted([0, 4])

array([0, 3])

In [29]:
ser.searchsorted([1, 3], side="right")

array([1, 3])

In [30]:
ser.searchsorted([1, 3], side="left")

array([0, 2])

In [31]:
ser = pd.Series([3, 1, 2])

In [32]:
ser.searchsorted([0, 3], sorter=np.argsort(ser))

array([0, 2])

<a class="anchor" id="smallest_/_largest_values"></a>
### smallest / largest values

`Series` has the [`nsmallest()`](../reference/api/pandas.Series.nsmallest.html#pandas.Series.nsmallest "pandas.Series.nsmallest") and [`nlargest()`](../reference/api/pandas.Series.nlargest.html#pandas.Series.nlargest "pandas.Series.nlargest") methods which return the
smallest or largest \(n\) values. For a large `Series` this can be much
faster than sorting the entire Series and calling `head(n)` on the result.

In [33]:
s = pd.Series(np.random.permutation(10))
s

0    4
1    9
2    2
3    3
4    1
5    5
6    6
7    0
8    7
9    8
dtype: int64

In [34]:
s.sort_values()

7    0
4    1
2    2
3    3
0    4
5    5
6    6
8    7
9    8
1    9
dtype: int64

In [35]:
s.nsmallest(3)

7    0
4    1
2    2
dtype: int64

In [36]:
s.nlargest(3)

1    9
9    8
8    7
dtype: int64

`DataFrame` also has the `nlargest` and `nsmallest` methods.

In [37]:
df = pd.DataFrame(
    {
        "a": [-2, -1, 1, 10, 8, 11, -1],
        "b": list("abdceff"),
        "c": [1.0, 2.0, 4.0, 3.2, np.nan, 3.0, 4.0],
    }
)

In [38]:
df.nlargest(3, "a")

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN

In [39]:
df.nlargest(5, ["a", "c"])

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN
2   1  d  4.0
6  -1  f  4.0

In [40]:
df.nsmallest(3, "a")

a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0

In [41]:
df.nsmallest(5, ["a", "c"])

a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0
2  1  d  4.0
4  8  e  NaN

<a class="anchor" id="sorting_by_a_multiindex_column"></a>
### Sorting by a MultiIndex column

You must be explicit about sorting when the column is a MultiIndex, and fully specify
all levels to `by`.

In [42]:
df1.columns = pd.MultiIndex.from_tuples(
    [("a", "one"), ("a", "two"), ("b", "three")]
)

In [43]:
df1.sort_values(by=("a", "two"))

a         b
  one two three
0   2   1     5
2   1   2     3
1   1   3     4
3   1   4     2