<img src="../../../images/banners/data_processing.png" width="600"/>

# <img src="../../../images/logos/python.png" width="23"/> Data Science Operations: Order, Aggregate

## <img src="../../../images/logos/toc.png" width="20"/> Table of Contents 
* [Transposing, Sorting, and Concatenating](#transposing,_sorting,_and_concatenating)
* [Aggregating](#aggregating)

---

<a class="anchor" id="transposing,_sorting,_and_concatenating"></a>


## Transposing, Sorting, and Concatenating

Other manipulations, while not quite as common as indexing or filtering, can also be very handy depending on the situation you’re in. You’ll see a few examples in this section.

Here’s **transposing** an array:

In [27]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

In [28]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

When you calculate the transpose of an array, the row and column indices of every element are switched. Item `[0, 2]`, for example, becomes item `[2, 0]`. You can also use `a.T` as an alias for `a.transpose()`.

The following code block shows sorting, but you’ll also see a more powerful sorting technique in the coming section on structured data:

In [4]:
import numpy as np

data = np.array([
    [7, 1, 4],
    [8, 6, 5],
    [1, 2, 3]
])

In [5]:
data

array([[7, 1, 4],
       [8, 6, 5],
       [1, 2, 3]])

In [6]:
np.sort(data)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [7]:
np.sort(data, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.sort(data, axis=0)

array([[1, 1, 3],
       [7, 2, 4],
       [8, 6, 5]])

In [10]:
np.sort(data, axis=1)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

Omitting the `axis` argument automatically selects the last and innermost dimension, which is the rows in this example. Using `None` flattens the array and performs a global sort. Otherwise, you can specify which axis you want. In output of `np.sort(data, axis=0)`, each column of the array still has all of its elements but they have been sorted low-to-high inside that column.

Finally, here’s an example of **concatenation**. While there’s a `np.concatenate()` function, there are also a number of helper functions that are sometimes easier to read.

Here are some examples:

In [33]:
import numpy as np

a = np.array([
    [4, 8],
    [6, 1]
])

b = np.array([
    [3, 5],
    [7, 2],
])


In [34]:
a

array([[4, 8],
       [6, 1]])

In [35]:
b

array([[3, 5],
       [7, 2]])

In [36]:
np.hstack((a, b))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [37]:
np.vstack((b, a))

array([[3, 5],
       [7, 2],
       [4, 8],
       [6, 1]])

In [38]:
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [39]:
np.concatenate((a, b), axis=0)

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [40]:
np.concatenate((a, b), axis=1)

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [41]:
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

`np.hstack((a, b))` and `np.vstack((b, a))` show the slightly more intuitive functions `hstack()` and `vstack()`. `np.concatenate((a, b))` and `np.concatenate((a, b), axis=None)` show the more generic `concatenate()`, first without an `axis` argument and then with `axis=None`. This flattening behavior is similar in form to what you just saw with `sort()`.

One important stumbling block to note is that all these functions take a tuple of arrays as their first argument rather than a variable number of arguments as you might expect. You can tell because there’s an extra pair of parentheses.

<a class="anchor" id="aggregating"></a>


## Aggregating

Your last stop on this tour of functionality before diving into some more advanced topics and examples is **aggregation**. You’ve already seen quite a few aggregating methods, including `.sum()`, `.max()`, `.mean()`, and `.std()`. You can reference NumPy’s larger library of [functions](https://numpy.org/doc/stable/reference/routines.html) to see more. Many of the mathematical, financial, and statistical functions use aggregation to help you reduce the number of dimensions in your data.